title: Working With OpenLearn Curriculum Assets
author: Tony Hirst
copyright: "2022" 
only_build_toc_files: true

execute:
  execute_notebooks: auto
  timeout: 60  
parse:
  myst_dmath_double_inline: true

sphinx:
  config:
    html_copy_source: false
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
