name: renderbook
on:
  push:
    branches:
      - main
    paths:
      - src/_build/html/**
  release:
    types: [published]
  workflow_dispatch:
       

jobs:
  checkout-and-deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Deploy to GitHub Pages
       if: success()
       uses: peaceiris/actions-gh-pages@v3.6.1
       with:
         publish_dir: src/_build/html
         github_token: ${{ secrets.GITHUB_TOKEN }}
